# randomly transform training patterns
random_transforms: true
# Cosine annealing learning rate
# scheduler
cosine_annealing: true
# apply fix for class imbalance with
# custom class weights
class_imbalance_fix: true
epochs: 30
batch_size: 16