# randomly transform training patterns
random_transforms: False

# Cosine annealing learning rate
# scheduler
cosine_annealing: False

# apply fix for class imbalance with
# custom class weights
class_imbalance_fix: False
epochs: 50
batch_size: 32

freeze_encoder: False

# "unet", "resnet", "fcn", or "new_arch"
model_type: fcn

# model identifier for save location of best model, figures and data
model_identifier: part3